Importing Libraries


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Importing dataset

In [ ]:
dataset = pd.read_csv('Iris.csv')

In [ ]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(X)

[[1.00e+00 5.10e+00 3.50e+00 1.40e+00 2.00e-01]
 [2.00e+00 4.90e+00 3.00e+00 1.40e+00 2.00e-01]
 [3.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [4.00e+00 4.60e+00 3.10e+00 1.50e+00 2.00e-01]
 [5.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01]
 [6.00e+00 5.40e+00 3.90e+00 1.70e+00 4.00e-01]
 [7.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01]
 [8.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [9.00e+00 4.40e+00 2.90e+00 1.40e+00 2.00e-01]
 [1.00e+01 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [1.10e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [1.20e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01]
 [1.30e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [1.40e+01 4.30e+00 3.00e+00 1.10e+00 1.00e-01]
 [1.50e+01 5.80e+00 4.00e+00 1.20e+00 2.00e-01]
 [1.60e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01]
 [1.70e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.80e+01 5.10e+00 3.50e+00 1.40e+00 3.00e-01]
 [1.90e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [2.00e+01 5.10e+00 3.80e+00 1.50e+00 3.00e-01]
 [2.10e+01 5.40e+00 3.40e+00 1.70e+00 2.

In [ ]:
print(y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

Handling Missing Values


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(X)
X = imputer.transform(X)

In [ ]:
print(X)

[[1.00e+00 5.10e+00 3.50e+00 1.40e+00 2.00e-01]
 [2.00e+00 4.90e+00 3.00e+00 1.40e+00 2.00e-01]
 [3.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [4.00e+00 4.60e+00 3.10e+00 1.50e+00 2.00e-01]
 [5.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01]
 [6.00e+00 5.40e+00 3.90e+00 1.70e+00 4.00e-01]
 [7.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01]
 [8.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [9.00e+00 4.40e+00 2.90e+00 1.40e+00 2.00e-01]
 [1.00e+01 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [1.10e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [1.20e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01]
 [1.30e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [1.40e+01 4.30e+00 3.00e+00 1.10e+00 1.00e-01]
 [1.50e+01 5.80e+00 4.00e+00 1.20e+00 2.00e-01]
 [1.60e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01]
 [1.70e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.80e+01 5.10e+00 3.50e+00 1.40e+00 3.00e-01]
 [1.90e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [2.00e+01 5.10e+00 3.80e+00 1.50e+00 3.00e-01]
 [2.10e+01 5.40e+00 3.40e+00 1.70e+00 2.

Encoding Categorical Data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(), [-1])], remainder = 'passthrough')
y = np.array(ct.fit_transform(y.reshape(-1,1)))

In [ ]:
print(y)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

Train-Test split

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [ ]:
print(X_train)

[[9.30e+01 5.80e+00 2.60e+00 4.00e+00 1.20e+00]
 [1.38e+02 6.40e+00 3.10e+00 5.50e+00 1.80e+00]
 [8.20e+01 5.50e+00 2.40e+00 3.70e+00 1.00e+00]
 [3.40e+01 5.50e+00 4.20e+00 1.40e+00 2.00e-01]
 [1.11e+02 6.50e+00 3.20e+00 5.10e+00 2.00e+00]
 [1.01e+02 6.30e+00 3.30e+00 6.00e+00 2.50e+00]
 [1.10e+02 7.20e+00 3.60e+00 6.10e+00 2.50e+00]
 [5.10e+01 7.00e+00 3.20e+00 4.70e+00 1.40e+00]
 [7.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01]
 [1.20e+02 6.00e+00 2.20e+00 5.00e+00 1.50e+00]
 [1.05e+02 6.50e+00 3.00e+00 5.80e+00 2.20e+00]
 [5.90e+01 6.60e+00 2.90e+00 4.60e+00 1.30e+00]
 [1.39e+02 6.00e+00 3.00e+00 4.80e+00 1.80e+00]
 [1.04e+02 6.30e+00 2.90e+00 5.60e+00 1.80e+00]
 [1.33e+02 6.40e+00 2.80e+00 5.60e+00 2.20e+00]
 [1.21e+02 6.90e+00 3.20e+00 5.70e+00 2.30e+00]
 [8.90e+01 5.60e+00 3.00e+00 4.10e+00 1.30e+00]
 [1.32e+02 7.90e+00 3.80e+00 6.40e+00 2.00e+00]
 [6.90e+01 6.20e+00 2.20e+00 4.50e+00 1.50e+00]
 [1.48e+02 6.50e+00 3.00e+00 5.20e+00 2.00e+00]
 [2.90e+01 5.20e+00 3.40e+00 1.40e+00 2.

In [ ]:
print(X_test)

[[1.50e+02 5.90e+00 3.00e+00 5.10e+00 1.80e+00]
 [3.10e+01 4.80e+00 3.10e+00 1.60e+00 2.00e-01]
 [1.30e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [4.80e+01 4.60e+00 3.20e+00 1.40e+00 2.00e-01]
 [3.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [1.37e+02 6.30e+00 3.40e+00 5.60e+00 2.40e+00]
 [6.10e+01 5.00e+00 2.00e+00 3.50e+00 1.00e+00]
 [2.80e+01 5.20e+00 3.50e+00 1.50e+00 2.00e-01]
 [8.00e+01 5.70e+00 2.60e+00 3.50e+00 1.00e+00]
 [1.02e+02 5.80e+00 2.70e+00 5.10e+00 1.90e+00]
 [1.12e+02 6.40e+00 2.70e+00 5.30e+00 1.90e+00]
 [1.16e+02 6.40e+00 3.20e+00 5.30e+00 2.30e+00]
 [9.90e+01 5.10e+00 2.50e+00 3.00e+00 1.10e+00]
 [9.50e+01 5.60e+00 2.70e+00 4.20e+00 1.30e+00]
 [1.35e+02 6.10e+00 2.60e+00 5.60e+00 1.40e+00]
 [9.10e+01 5.50e+00 2.60e+00 4.40e+00 1.20e+00]
 [2.40e+01 5.10e+00 3.30e+00 1.70e+00 5.00e-01]
 [8.10e+01 5.50e+00 2.40e+00 3.80e+00 1.10e+00]
 [2.50e+01 4.80e+00 3.40e+00 1.90e+00 2.00e-01]
 [7.00e+01 5.60e+00 2.50e+00 3.90e+00 1.10e+00]
 [1.20e+01 4.80e+00 3.40e+00 1.60e+00 2.

In [ ]:
print(y_train)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0.

In [ ]:
print(y_test)

[[0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


Training the Multiple Linear Regression Model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = regressor.predict(X_test)
#np.set_printoptions(precision=2)
#print(np.concatenate((y_pred.reshape(len(y_pred),3),y_test.reshape(len(y_test),1)),3))
print(y_pred)

[[ 0.03 -0.03  1.  ]
 [ 0.82  0.32 -0.14]
 [ 0.83  0.49 -0.32]
 [ 0.9   0.05  0.05]
 [ 0.87  0.46 -0.33]
 [-0.03 -0.07  1.1 ]
 [ 0.1   0.96 -0.06]
 [ 0.96  0.11 -0.07]
 [ 0.31  0.45  0.24]
 [-0.11  0.56  0.55]
 [-0.09  0.47  0.62]
 [-0.01  0.12  0.89]
 [ 0.39  0.14  0.47]
 [ 0.14  0.46  0.4 ]
 [-0.17  0.57  0.6 ]
 [ 0.05  0.66  0.29]
 [ 0.84  0.24 -0.07]
 [ 0.17  0.63  0.2 ]
 [ 0.79  0.38 -0.17]
 [ 0.15  0.73  0.11]
 [ 0.85  0.4  -0.25]
 [ 0.83  0.51 -0.34]
 [-0.14  0.32  0.82]
 [ 0.07  0.09  0.83]
 [-0.09  0.34  0.74]
 [-0.25  0.75  0.49]
 [ 0.05  0.58  0.38]
 [ 0.21  0.33  0.47]
 [-0.24  0.77  0.47]
 [ 0.2   0.32  0.48]]


In [ ]:


for i in y_pred:
  if i[0] == max(i[0],i[1],i[2]):
    print('Iris-setosa')
  elif i[1] == max(i[0],i[1],i[2]):
    print('Iris-versicolor')
  else:
    print('Iris-virginica')

Iris-virginica
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-virginica
Iris-versicolor
Iris-setosa
Iris-versicolor
Iris-versicolor
Iris-virginica
Iris-virginica
Iris-virginica
Iris-versicolor
Iris-virginica
Iris-versicolor
Iris-setosa
Iris-versicolor
Iris-setosa
Iris-versicolor
Iris-setosa
Iris-setosa
Iris-virginica
Iris-virginica
Iris-virginica
Iris-versicolor
Iris-versicolor
Iris-virginica
Iris-versicolor
Iris-virginica


In [ ]:
for i in y_test:
  if i[0] == max(i[0],i[1],i[2]):
    print('Iris-setosa')
  elif i[1] == max(i[0],i[1],i[2]):
    print('Iris-versicolor')
  else:
    print('Iris-virginica')

Iris-virginica
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-virginica
Iris-versicolor
Iris-setosa
Iris-versicolor
Iris-virginica
Iris-virginica
Iris-virginica
Iris-versicolor
Iris-versicolor
Iris-virginica
Iris-versicolor
Iris-setosa
Iris-versicolor
Iris-setosa
Iris-versicolor
Iris-setosa
Iris-setosa
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
Iris-versicolor
Iris-versicolor
Iris-virginica
Iris-versicolor


In [ ]:
from sklearn import metrics
print(metrics.mean_absolute_error(y_pred,y_test))

0.26687529873134674
